services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8095:8095"

  loan-service:
    build:
      context: ./loan-service
      dockerfile: Dockerfile
    container_name: loan-service
    ports:
      - "8096:8096"

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8097:8097"

  gateway-app:
    build:
      context: ./gateway-app
      dockerfile: Dockerfile
    container_name: gateway-app
    ports:
      - "8090:8090"